### ISSUE TITLE
[Backend] Create User Account

### ISSUE THREAD

**Issue by benessilfie** [Slightly-Techie/ecommerce-api#11]
Summary: User account creation

**Acceptance Criteria** 

- [x] User model should have these attributes: refer [here](https://dbdiagram.io/d/644901806b3194705139ca09)
- [x] User's password should be encrypted (check out the `bcrypt gem`)
- [x] Username field should be unique to each user
- [x] Users should be able to create an account
- [x] There should be an after create call back that sends the confirmation token on the user model to user's email

**Resources** 
- For email validation checkout the `email_address` gem

**Comment by benessilfie** [comment]
@greatnessmensah @blitzblade How is it going on the ticket?

**Comment by blitzblade** [comment]
> @greatnessmensah @blitzblade How is it going so far?
> 
> A couple of tasks are blocked waiting on you

Ei me??? I didn't know oo
