### ISSUE TITLE
[Backend] Setup Action Mailer

### ISSUE THREAD

**Issue by benessilfie** [Slightly-Techie/ecommerce-api#14]
Summary: setup action mailer to be used to send emails in our app

**Acceptance Criteria** 

- [x] There should be a welcome email template what will send a token to users to confirm their email address
- [x] There should be a forgot password email template to send a token to users when did they click on forgot password

**Comment by benessilfie** [comment]
@JerryAgbesi I thought we were doing this together 🥲🥲

**Comment by JerryAgbesi** [comment]
So sorry Sir, I had just started looking in the whole Action Mailer thing.

**Comment by JerryAgbesi** [comment]
Please I'll wait for you wai 😂

**Comment by benessilfie** [comment]
lol let me know when you are ready @JerryAgbesi

**Comment by JerryAgbesi** [comment]
Ohk we can do it when you are free. Would tomorrow be fine? @benessilfie

**Comment by benessilfie** [comment]
That works!
